### PR TITLE
Fix Fluid Router GUI crash

### LINKED ISSUE #6172: Fluid router GUI IllegalStateException: Cannot encode empty FluidStack
### Minecraft Version

1.21.1

### Immersive Engineering Version

12.1.0-185

### How did it happen?

Clicking in any of the fluid filter slots causes this crash `IllegalStateException: Cannot encode empty FluidStack`

### Crash Log

https://gnomebot.dev/paste/mclogs/RQ9SyGp

### PR DESCRIPTION
**Pull request by leagris**
Fix #6172 by adding check for Empty fluid in `setFluidInSlot`
Fix Fluid Router not working on remote world (Multiplayer)

### CODE REVIEW

**Comment by leagris** [comment]
With this fix, the Fluid Router GUI no longer crashes with an Illegal State Exception.

I was finally able to configure it for my automated potion of Strength setup, feeding into my refinery with the goal of producing cetane-boosted diesel.

https://imgur.com/gallery/immersive-engineering-fixed-fluid-router-gui-crash-KLUogXg

screenshot
screenshot
screenshot

**Comment by leagris** [comment]
Noticed that the Fluid Router settings are not working at all on multiplayer. Nothing happens.
This needs more fixes

File: src/main/java/blusunrize/immersiveengineering/common/gui/FluidSorterMenu.java [hunk 1]
```diff
@@ -86,7 +90,8 @@ public void receiveMessageFromScreen(CompoundTag message)
 			int side = message.getInt("filter_side");
 			int slot = message.getInt("filter_slot");
 			FluidStack newFilter = FluidStack.parseOptional(
-					Minecraft.getInstance().level.registryAccess(),
+					((MinecraftServer)LogicalSidedProvider.WORKQUEUE.get(LogicalSide.SERVER)).overworld()
+							.registryAccess(),
```
Comment (BluSunrize) [inline src/main/java/blusunrize/immersiveengineering/common/gui/FluidSorterMenu.java]: Surely there is a cleaner way to do this? Maybe via the player?

Comment (leagris) [reply src/main/java/blusunrize/immersiveengineering/common/gui/FluidSorterMenu.java]: @BluSunrize if you have a moment please review the changes I made to this. I'd really like to go forward with some potion compatibility for this GUI.

**Comment by leagris** [comment]
@BluSunrize Is there anything else I need to change?
